# Generated by Django 6.0.1 on 2026-01-15 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (+)'), ('SALIDA', 'Salida (-)'), ('AJUSTE', 'Ajuste Manual')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('stock_previo', models.PositiveIntegerField()),
                ('stock_nuevo', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core.item')),
            ],
        ),
    ]
