# Generated by Django 6.0.1 on 2026-01-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='item',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Referencial'),
        ),
    ]
