# Generated by Django 6.0.1 on 2026-01-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_descripcion_item_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
